baidu/san-website

source/_posts/practice/higher-communication.md

feat practice: higher-communication

---

source/_posts/practice/child-to-parent.md

add child-to-parent

---

package.json
source/_posts/tutorial/background.md
themes/san/layout/_partial/recommend.ejs

san教程增加背景: 什么是MVVM

---

source/_posts/practice/position-absolute-dom.md
source/_posts/practice/posotion-absolute-dom.md
themes/san/layout/practice.ejs

add posotion-absolute-dom practice

add posotion-absolute-dom practice

---

source/_posts/practice/array-deep-updates-trigger-view.md

firstData改为firstNews

---

source/_posts/practice/dynamic-parent-child.md
themes/san/layout/practice.ejs

docs(doc): add dynamic parent and child message commit.

---

source/_posts/practice/dynamic-parent-child.md
themes/san/layout/practice.ejs

fix(doc): 修改动态父子组件之间的通信的实例

---

source/_posts/practice/dynamic-parent-child.md

修改文档codepen 展示形式

---

source/_posts/tutorial/component.md

doc:补充使用class创建组件时contructor使用应注意的初始化参数

---

README.md
themes/san/layout/_partial/footer.ejs
themes/san/layout/practice.ejs

更新实践类文档目录&&README增加san 文档贡献规范

---

source/_posts/tutorial/start.md

在教程开始部分，加入San介绍

---

source/_posts/tutorial/setup.md

fixed https://github.com/ecomfe/san/issues/193

fixed documentation

---

package.json
themes/san/layout/_partial/recommend.ejs

- doc:add san-factory
- dep:update hexo for security issues.

添加san-factory链接、升级hexo

---

source/_posts/practice/dynamic-parent-child.md

Uncaught TypeError: Cannot read property 'push' of undefined
at pen.js:36
at Array.forEach (<anonymous>)
at t.addChild (pen.js:28)
at t.re (san.min.js:1)

这里还是有报错，是否是 child > children

---

source/_posts/en/tutorial/event.md
source/_posts/en/tutorial/for.md
source/_posts/en/tutorial/form.md

[translate] for.md + form.md

---

source/_posts/en/tutorial/style.md

translate tutorial/style

---

source/_posts/en/practice/auto-camel.md

[translate] env/practice/auto-camel.md

---

source/_posts/en/practice/child-to-grandparent.md

translate practice/child-to-grandparent

---

source/_posts/en/tutorial/style.md

虽然 https://github.com/baidu/san-website/pull/94 合入了tutorial/style，但https://github.com/baidu/san-website/pull/93 有相关评论，已照着修改。（由于提交姿势有误，style.md出现在2个pr里， 现93已关闭）。

translate tutorial/style #65

---

source/_posts/en/practice/question-and-answer.md

translate practice/question-and-answer

---

source/_posts/en/practice/position-absolute-dom.md

translate position-absolute-dom

---

themes/san/languages/en.yml

translate `example` and `feature`

---

package.json
source/_posts/doc/api.md

ref和el的文档进行补充说明

---

source/_posts/en/tutorial/for.md
source/_posts/en/tutorial/if.md

原文 https://github.com/baidu/san-website/commit/1e4a737dc1354c59be7c9c72786270f47a9cb05c

docs: translate `fragment` in `if` and `for`

---

themes/san/layout/_partial/recommend.ejs
themes/san/layout/index.ejs

update san-loader url

---

source/_posts/tutorial/slot.md

Updatec slot.md: fix some error

---

source/_posts/tutorial/reverse.md
themes/san/languages/default.yml
themes/san/languages/en.yml
themes/san/layout/_partial/header.ejs

添加github discussion链接

---

source/_posts/en/practice/san-composition-api.md
source/_posts/practice/san-composition-api.md
themes/san/languages/default.yml
themes/san/languages/en.yml
themes/san/layout/_partial/recommend.ejs
themes/san/layout/index.ejs
themes/san/layout/practice.ejs

在首页、指南、周边3个位置添加 san-composition:
首页
周边
指南：
文章：

docs: add docs for san-composition
